{{- define "common.pvc.tpl" -}}
{{- range .Values.volumes }}
{{- if not (or .existingClaim .hostPath .fileName .emptyDir .existingConfigMap .existingSecret .ephemeral) }}
{{- $robustName := include "common.robustName" $.Release.Name }}
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ printf "%s-%s" $robustName .name }}
  namespace: {{ $.Release.Namespace }}
  {{- if .pvcAnnotations }}
  annotations:
    {{- toYaml .pvcAnnotations | nindent 4 }}
  {{- end }} 
spec:
  {{- include "common.volumeClaimSpec.tpl" . | nindent 2 }}
{{- end }}
{{- end }}
{{- end -}}
